# This file is copied from your project sources.
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11" # Matches your project's requirement

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  install:
    # Install the project itself and its dependencies
    - method: pip
      path: .
    # Install the documentation-specific requirements
    - requirements: docs/requirements.txt

formats:
  - html
  - pdf
  - epub