"""Add public_key_pem to Request table.

Revision ID: e7169fe29ea1
Revises: 0b01b44ab005
Create Date: 2025-10-09 13:23:30.141015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7169fe29ea1"
down_revision: Union[str, Sequence[str], None] = "0b01b44ab005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("requests", sa.Column("public_key_pem", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "public_key_pem")
    # ### end Alembic commands ###
